### ISSUE TITLE
Add dealID (or alike) to Value

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/go-indexer-core#13]
Per https://github.com/filecoin-project/indexer-reference-provider/issues/15, we'll need to update `indexer.Value` to include a contextual ID (like a `dealID`) to identify updates over metadata for the same CID. 

This will also mean slightly changing how the indexer-core behaves on `Put`. A `Put` for the same `dealID` shouldn't append a new entry but update the existing one. 

```go
// Value is the value of an index entry that is stored for each CID in the indexer.
type Value struct {
       // Contextual ID used to identify different entries.
        DealID cid.Cid
	// PrividerID is the peer ID of the provider of the CID
	ProviderID peer.ID
	// Metadata is serialized data that provides information about retrieving
	// data, for the indexed CID, from the identified provider.
	Metadata []byte
}
```
// cc @gammazero

**Comment by gammazero** [comment]
Originally, old values would be removed and new ones would be added (no value update), and the provider would tell the indexer which to remove.  We were assuming that the metadata likely would be the deal ID.  So, a put with the same metadata (same deal ID) would not append a new entry, or update it.

What this issue is asking for is to separate the deal ID from the metadata, and use only that portion to determine the existence of an entry that can now also be updated. 

Does this change how deleting a value works also: to only match the ProviderID and DealID instead of the entire metadata to identify the value to delete?

Summary of new logic for Put(CID, providerID, dealID, metadata):
- No values for CID --> Add value for CID
- Existing values for CID -->
  - Existing value matches providerID only --> Append new value to list of values for CID
  - Existing value matches providerID and dealID --> Replace existing value
  - Existing value matches providerID, dealID, and metadata --> no op

Does this look correct?

**Comment by adlrocha** [comment]
>  We were assuming that the metadata likely would be the deal ID

After a conversation yesterday with the Ignite team, apparently metadata will include additional information such as the price of a deal. IIRC, with the current logic a price update for a deal would mean an append for the CID/providerID, while in this case, the correct thing to do would be to replace it. 

> Does this look correct?

I think this is perfect.

**Comment by gammazero** [comment]
1. Since we are moving from CIDs to multihashes, what should the context ID  (deal ID) become:
  - Remain a CID
  - Become a multihash
  - Become an opaque byte slize
  
  2. Since we are going to use hashed multihashes, does the context ID (deal ID) also need to be hashed?

**Comment by willscott** [comment]
1: i'm okay with any of these. we can leave it as CID, or change to opaque byte slice.
2: nope, don't think so, it's really just an arbitrary identifier chosen by the provider.

**Comment by adlrocha** [comment]
For 1, I'll personally go with CIDs. This is up to the provider, but I think miners speak the CID-language already for dealIDs.

**Comment by adlrocha** [comment]
Update: According to the latest changes in https://github.com/filecoin-project/indexer-reference-provider/pull/21, and the potential use from other teams, we should make `contextID` a `[]byte`.
